language: R
cache: packages

git:
        submodules: false

matrix:
  include:
    - os: linux
      dist: precise
      r: oldrel
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
      r: release
    - os: linux
      dist: trusty
      r: devel
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode8.3
      brew_packages: poppler
      r: oldrel
    - os: osx
      osx_image: xcode8.3
      brew_packages: poppler
      r: release
    - os: osx
      osx_image: xcode8.3
      brew_packages: poppler
      r: devel

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change


r_github_packages:
        - RcppCore/Rcpp
        - ropensci/pdftools
        - jimhester/covo

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
    
after_success:
- if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
